# Translations template for PROJECT.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2023-12-24 18:20+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.13.1\n"

#: commands.py:27
msgid "At your service."
msgstr ""

#: commands.py:49
msgid "Your chat history with assistant was erased."
msgstr ""

#: commands.py:51
msgid "You have no chat history with assistant to erase."
msgstr ""

#: commands.py:57
msgid "Hello *{0}*!"
msgstr ""

#: commands.py:64
msgid "help_message"
msgstr ""

#: keyboards.py:15
msgid "GPT Provider"
msgstr ""

#: keyboards.py:17
msgid "Language"
msgstr ""

#: keyboards.py:19
msgid "❌Delete"
msgstr ""

#: keyboards.py:36 keyboards.py:51
msgid "↩️Back"
msgstr ""

#: middlewares.py:75
msgid "This is not your request"
msgstr ""

#: settings.py:21 settings.py:26
msgid "Settings⚙️"
msgstr ""

#: settings.py:35
msgid "Choose your GPT provider. By default AiChatOnline is enabled."
msgstr ""

#: settings.py:43
msgid "You chose the same provider."
msgstr ""

#: settings.py:46
msgid "Provider was changed"
msgstr ""

#: settings.py:55
msgid "Choose your language:"
msgstr ""

#: settings.py:64
msgid "You chose the same language"
msgstr ""

#: settings.py:67
msgid "Language have been changed."
msgstr ""

#: settings.py:73
msgid "Settings were deleted."
msgstr ""

#: modules/ChatGPT/chatgpt.py:126
msgid "Generating..."
msgstr ""

#: modules/ChatGPT/chatgpt.py:137
msgid "Sorry, no provider has responded."
msgstr ""

#: modules/ChatGPT/chatgpt.py:156
msgid "Too many requests. Changing provider to {0} and retrying."
msgstr ""

#: modules/ChatGPT/chatgpt.py:160
msgid ""
"Sorry, your message wasn't handled properly. Please retry or try to clear"
" your history."
msgstr ""

#: modules/ChatGPT/chatgpt.py:177
msgid "Sorry, some problem occurred. Changing provider to {0} and retrying"
msgstr ""

#: modules/audio/audio.py:42 modules/images/text_recognition.py:28
msgid "Couldn't recognize anything."
msgstr ""

#: modules/audio/audio.py:77
msgid "Sorry, some problem occurred during transcription."
msgstr ""

#: modules/images/image_generation.py:51 modules/images/image_generation.py:65
msgid "Sorry, some problem occurred"
msgstr ""

#: modules/images/image_generation.py:69
msgid ""
"Please, provide a prompt. Add it after the command or just reply with "
"this command to the prompt."
msgstr ""

#: modules/images/images_handler.py:26
msgid "Recognize text"
msgstr ""

#: modules/images/images_handler.py:29
msgid "What do you want to do with the image?"
msgstr ""

#: modules/images/text_recognition.py:58
msgid "Sorry, some problem occurred during recognition."
msgstr ""

#: modules/tiktok/tiktok.py:28
msgid "Downloading the video..."
msgstr ""

#: modules/tiktok/tiktok.py:48
msgid "Couldn't download the video"
msgstr ""

#: modules/yt/youtube.py:58 modules/yt/youtube.py:80
msgid "Choose type/resolution"
msgstr ""

#: modules/yt/youtube.py:88
msgid "Sorry, filesize of this video is greater than the limit (50 Mb)"
msgstr ""

